// Generate supabase/seed_schedule.sql from the 2026 weekly schedule workbook.
//
// Run: NODE_PATH=node_modules node --experimental-strip-types \
//        scripts/generate-seed-schedule.ts <in.xlsx> supabase/seed_schedule.sql
//
// Uses the same parser as the in-app upload route (src/lib/importSchedule.ts), so the loaded
// data and an uploaded file produce identical rows. Idempotent: employees by name, shifts by
// (employee, date, start, end), so it is safe to run on top of seed.sql and safe to re-run.

import XLSX from "xlsx";
import { createHash } from "node:crypto";
import { writeFileSync } from "node:fs";
import { parseSchedule } from "../src/lib/importSchedule.ts";

const IN = process.argv[2] || "/tmp/schedule.xlsx";
const OUT = process.argv[3] || "supabase/seed_schedule.sql";
const STORE = "11111111-1111-1111-1111-111111111111";
const OWNER = "33333333-0000-0000-0000-000000000001";

// Our department ids by lowercased name (from seed.sql), for the parser to map onto.
const DEPT: Record<string, string> = {
  hardware: "22222222-0000-0000-0000-000000000001",
  gifts: "22222222-0000-0000-0000-000000000002",
  grocery: "22222222-0000-0000-0000-000000000003",
  bakery: "22222222-0000-0000-0000-000000000004",
  clothing: "22222222-0000-0000-0000-000000000005",
  produce: "22222222-0000-0000-0000-000000000006",
  meat: "22222222-0000-0000-0000-000000000007",
  "chip stand": "22222222-0000-0000-0000-000000000008",
  "garden center": "22222222-0000-0000-0000-000000000009"
};

const uuid = (k: string) => {
  const h = createHash("md5").update(k).digest("hex");
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-${h.slice(12, 16)}-${h.slice(16, 20)}-${h.slice(20, 32)}`;
};
const q = (v: string | null) => (v == null || v === "" ? "null" : `'${String(v).replace(/'/g, "''")}'`);

const wb = XLSX.readFile(IN);
const sheets = wb.SheetNames.map((n) => ({
  name: n,
  rows: XLSX.utils.sheet_to_json(wb.Sheets[n], { header: 1, blankrows: false, defval: null }) as any[][]
}));
const p = parseSchedule(sheets, DEPT);

const out: string[] = [];
out.push("-- GENERATED by scripts/generate-seed-schedule.ts from the 2026 weekly schedule workbook.");
out.push("-- Employees and shifts. Run AFTER schema.sql and seed.sql (it needs the departments).");
out.push("-- Idempotent: employees by name, shifts by (employee, date, start, end). Safe to re-run.");
out.push("");

for (const name of p.employees) {
  const id = uuid(`emp|${STORE}|${name.toLowerCase()}`);
  out.push("insert into employee (id, store_id, full_name, status)");
  out.push(`  select '${id}', '${STORE}', ${q(name)}, 'active'`);
  out.push(`  where not exists (select 1 from employee where store_id = '${STORE}' and lower(full_name) = lower(${q(name)}));`);
}
out.push("");

for (const s of p.shifts) {
  const id = uuid(`shift|${s.employeeName.toLowerCase()}|${s.workDate}|${s.startTime}|${s.endTime}|${s.departmentKey}`);
  const dept = s.departmentId ? `'${s.departmentId}'` : "null";
  const note = s.departmentId ? "null" : q(s.departmentKey); // keep the label (checkout, flyers) when it has no department
  out.push("insert into shift (id, employee_id, department_id, work_date, start_time, end_time, notes, created_by)");
  out.push(`  select '${id}', (select id from employee where store_id = '${STORE}' and lower(full_name) = lower(${q(s.employeeName)}) limit 1), ${dept}, '${s.workDate}', '${s.startTime}', '${s.endTime}', ${note}, '${OWNER}'`);
  out.push(`  where not exists (select 1 from shift sh join employee e on e.id = sh.employee_id where e.store_id = '${STORE}' and lower(e.full_name) = lower(${q(s.employeeName)}) and sh.work_date = '${s.workDate}' and sh.start_time = '${s.startTime}' and sh.end_time = '${s.endTime}');`);
}

writeFileSync(OUT, out.join("\n"));
console.log("OUT:", OUT);
console.log("summary:", JSON.stringify(p.summary));
